# Generated by Django 5.2.6 on 2025-10-11 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_emailotp'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='emailotp',
            name='authenticat_email_9cfae5_idx',
        ),
        migrations.AddField(
            model_name='emailotp',
            name='raw_otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='emailotp',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
