# Generated by Django 5.2.6 on 2025-10-12 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_remove_emailotp_authenticat_email_9cfae5_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailotp',
            name='attempts',
        ),
        migrations.RemoveField(
            model_name='emailotp',
            name='used',
        ),
        migrations.AlterField(
            model_name='emailotp',
            name='otp_hash',
            field=models.CharField(max_length=64),
        ),
    ]
