# Generated by Django 5.2.6 on 2025-11-20 22:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_user_referral_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AddField(
            model_name='vendor',
            name='category',
            field=models.CharField(blank=True, choices=[('food', 'Food'), ('beverage', 'Beverage'), ('nightlife', 'Nightlife'), ('grocery', 'Grocery'), ('pharmacy', 'Pharmacy'), ('electronics', 'Electronics'), ('fashion', 'Fashion'), ('others', 'Others')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='is_profile_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendor',
            name='shop_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='shop_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='vendor_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='business_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='geofence_radius',
            field=models.FloatField(blank=True, default=100.0, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
