# Generated by Django 5.2.6 on 2025-10-12 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_remove_emailotp_attempts_remove_emailotp_used_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailotp',
            name='attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='emailotp',
            name='used',
            field=models.BooleanField(default=False),
        ),
    ]
