# Generated by Django 5.2.6 on 2025-11-20 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_remove_user_username_vendor_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='business_name',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='geofence_radius',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='location',
        ),
        migrations.AddField(
            model_name='vendor',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='phone_number',
            field=models.CharField(default='N/A', max_length=15),
        ),
        migrations.AddField(
            model_name='vendor',
            name='shop_images',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='category',
            field=models.CharField(choices=[('food', 'Food'), ('beverage', 'Beverage'), ('nightlife', 'Nightlife'), ('grocery', 'Grocery'), ('pharmacy', 'Pharmacy'), ('electronics', 'Electronics'), ('fashion', 'Fashion'), ('others', 'Others')], default='others', max_length=20),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='shop_address',
            field=models.TextField(default='N/A'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='shop_name',
            field=models.CharField(default='N/A', max_length=150),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='vendor_name',
            field=models.CharField(default='N/A', max_length=100),
        ),
    ]
