# Generated by Django 5.2.6 on 2025-11-22 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_vendorprofileupdaterequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorprofileupdaterequest',
            name='nid_back',
            field=models.ImageField(blank=True, null=True, upload_to='vendor_update_docs/'),
        ),
        migrations.AddField(
            model_name='vendorprofileupdaterequest',
            name='nid_front',
            field=models.ImageField(blank=True, null=True, upload_to='vendor_update_docs/'),
        ),
        migrations.AddField(
            model_name='vendorprofileupdaterequest',
            name='trade_license',
            field=models.FileField(blank=True, null=True, upload_to='vendor_update_docs/'),
        ),
        migrations.AddField(
            model_name='vendorprofileupdaterequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='vendorprofileupdaterequest',
            name='new_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
