# Generated by Django 5.2.6 on 2025-10-12 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_vendor_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
