# Generated by Django 5.2.6 on 2025-11-22 17:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_vendorprofileupdaterequest_nid_back_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorprofileupdaterequest',
            name='nid_back',
            field=models.ImageField(blank=True, null=True, upload_to='vendor_update_docs/nid/'),
        ),
        migrations.AlterField(
            model_name='vendorprofileupdaterequest',
            name='nid_front',
            field=models.ImageField(blank=True, null=True, upload_to='vendor_update_docs/nid/'),
        ),
        migrations.AlterField(
            model_name='vendorprofileupdaterequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_vendor_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vendorprofileupdaterequest',
            name='trade_license',
            field=models.FileField(blank=True, null=True, upload_to='vendor_update_docs/license/'),
        ),
    ]
