# Generated by Django 5.2.6 on 2025-11-22 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_alter_vendorprofileupdaterequest_nid_back_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='nid_back',
            field=models.ImageField(blank=True, null=True, upload_to='vendor_docs/nid/'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='nid_front',
            field=models.ImageField(blank=True, null=True, upload_to='vendor_docs/nid/'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='trade_license',
            field=models.FileField(blank=True, null=True, upload_to='vendor_docs/license/'),
        ),
    ]
