# Generated by Django 5.2.6 on 2025-11-22 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_vendor_nid_back_vendor_nid_front_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorprofileupdaterequest',
            name='shop_images',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
