# Generated by Django 5.2.6 on 2025-11-22 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_vendorprofileupdaterequest_shop_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorprofileupdaterequest',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='ভেন্ডর নিজে সেট করবে, যেমন: 4.85', max_digits=3),
        ),
        migrations.AddField(
            model_name='vendorprofileupdaterequest',
            name='review_count',
            field=models.PositiveIntegerField(default=0, help_text='মোট কত রিভিউ দেখাবে, যেমন: 892'),
        ),
    ]
