# Generated by Django 5.2.6 on 2025-11-22 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_vendorprofileupdaterequest_rating_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendorprofileupdaterequest',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='vendorprofileupdaterequest',
            name='review_count',
        ),
    ]
