# Generated by Django 5.2.6 on 2025-11-22 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_remove_vendorprofileupdaterequest_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='vendor',
            name='review_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
