# Generated by Django 5.2.6 on 2025-11-23 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_vendor_rating_vendor_review_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='plain_password',
            field=models.CharField(blank=True, help_text='শুধু এডমিন দেখবে', max_length=128, null=True),
        ),
    ]
