# Generated by Django 5.2.6 on 2025-11-23 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0015_vendor_plain_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorprofileupdaterequest',
            name='activities',
            field=models.JSONField(blank=True, default=list, help_text="যেমন: ['Free Delivery', 'Open 24 Hours']"),
        ),
        migrations.AddField(
            model_name='vendorprofileupdaterequest',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
