# Generated by Django 5.2.6 on 2025-11-23 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0016_vendorprofileupdaterequest_activities_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendorprofileupdaterequest',
            name='activities',
        ),
        migrations.RemoveField(
            model_name='vendorprofileupdaterequest',
            name='description',
        ),
        migrations.AddField(
            model_name='vendor',
            name='activities',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='vendor',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
