# Generated by Django 5.2.6 on 2025-11-23 23:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0017_remove_vendorprofileupdaterequest_activities_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteVendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_vendors', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='authentication.vendor')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'vendor')},
            },
        ),
    ]
