# Generated by Django 5.2.6 on 2025-11-30 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0018_favoritevendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='popup_viewed',
            field=models.BooleanField(default=False),
        ),
    ]
