# Generated by Django 5.2.6 on 2025-11-30 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0019_user_popup_viewed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='shop_images',
            field=models.ImageField(upload_to='vendor_shop_image/'),
        ),
    ]
