# Generated by Django 5.2.6 on 2025-11-30 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0020_alter_vendor_shop_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='vendor_shop_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='shop_images',
        ),
        migrations.AddField(
            model_name='vendor',
            name='shop_images',
            field=models.ManyToManyField(blank=True, to='authentication.vendorimage'),
        ),
    ]
