# Generated by Django 5.2.6 on 2025-12-02 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0021_vendorimage_remove_vendor_shop_images_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='shop_images',
            field=models.ManyToManyField(blank=True, related_name='vendors', to='authentication.vendorimage'),
        ),
        migrations.RemoveField(
            model_name='vendorprofileupdaterequest',
            name='shop_images',
        ),
        migrations.AddField(
            model_name='vendorprofileupdaterequest',
            name='shop_images',
            field=models.ManyToManyField(blank=True, related_name='update_requests', to='authentication.vendorimage'),
        ),
    ]
