# Generated by Django 5.2.6 on 2025-12-03 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0022_alter_vendor_shop_images_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='shop_images',
        ),
        migrations.RemoveField(
            model_name='vendorprofileupdaterequest',
            name='shop_images',
        ),
        migrations.RemoveField(
            model_name='user',
            name='popup_viewed',
        ),
        migrations.AddField(
            model_name='vendor',
            name='shop_images',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.DeleteModel(
            name='VendorImage',
        ),
        migrations.AddField(
            model_name='vendorprofileupdaterequest',
            name='shop_images',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
