# Generated by Django 5.2.6 on 2025-12-03 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0023_remove_vendor_shop_images_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first_login_done',
            field=models.BooleanField(default=False),
        ),
    ]
