# Generated by Django 5.2.6 on 2025-12-14 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0027_profile_latitude_profile_longitude'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favoritevendor',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='favoritevendor',
            name='ai_vendor_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='favoritevendor',
            name='ai_vendor_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='favoritevendor',
            name='expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='favoritevendor',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='authentication.vendor'),
        ),
        migrations.AlterUniqueTogether(
            name='favoritevendor',
            unique_together={('user', 'vendor', 'ai_vendor_id')},
        ),
    ]
