# Generated by Django 5.2.6 on 2025-12-17 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0029_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='aliffited_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
