# Generated by Django 5.2.6 on 2025-12-17 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0030_notification_aliffited_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='reward_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='shop_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
