# Generated by Django 5.2.6 on 2026-02-05 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0031_notification_reward_name_notification_shop_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
