# Generated by Django 5.2.6 on 2026-02-05 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0032_vendor_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='thumbnail_image',
            field=models.ImageField(blank=True, null=True, upload_to='vendor_thumbnail/'),
        ),
    ]
